language: java
script:
  - mvn --batch-mode checkstyle:check -Dcheckstyle.violationSeverity=warning | egrep -v '^\[INFO\] Download(ing|ed):'
  - mvn --batch-mode pmd:check | egrep -v '^\[INFO\] Download(ing|ed):'
  - mvn --batch-mode license:check | egrep -v '^\[INFO\] Download(ing|ed):'
  - mvn --batch-mode verify | egrep -v '^\[INFO\] Download(ing|ed):'
  - mvn --batch-mode jasmine:test | egrep -v '^\[INFO\] Download(ing|ed):'
after_success:
  - mvn --batch-mode jacoco:prepare-agent test jacoco:report coveralls:jacoco | egrep -v '^\[INFO\] Download(ing|ed):'

jdk:
  - oraclejdk8

branches:
  except:
  - /^(re|old)_.*$/

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

