language: java
script: mvn verify jasmine:test
after_success: mvn jacoco:prepare-agent test jacoco:report coveralls:jacoco

jdk:
  - openjdk7
  - oraclejdk7

branches:
  except:
  - /^(re|old)_.*$/

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

