language: java

before_script:
  - npm install -g bootlint

script:
  - ./src/main/scripts/ci/check-build-and-verify.sh

after_success:
  - ./src/main/scripts/ci/publish-code-coverage.sh

jdk:
  - oraclejdk8

branches:
  except:
  - /^(re|old)_.*$/

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

# We don't want to run `mvn install -DskipTests=true` for downloading project's dependencies
install: true
