language: java
script: mvn verify jasmine:test

jdk:
  - openjdk6

branches:
  except:
  - /^(re|old)_.*$/

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

