language: java
script:
  - mvn verify jasmine:test
  - mvn -Pit clean verify thucydides:aggregate

jdk:
  - openjdk6

branches:
  except:
  - /^(re|old)_.*$/

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

